name: Build and Deploy

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      gem-dir: vendor/bundle
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Ruby
        uses: ruby/setup-ruby@v1

      - name: Use cached deps
        uses: actions/cache@v1
        with:
          path: ${{ env.gem-dir }}
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install deps
        run: |
          bundle config path ${{ env.gem-dir }}
          bundle install --jobs 4 --retry 3

      - name: Build
        run: bundle exec jekyll build

      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
